/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Balloon.glb -o src/components/Balloon.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Balloon(props) {
  const { nodes, materials } = useGLTF("/models/Balloon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Balloon007"
        geometry={nodes.Balloon007.geometry}
        material={materials.phong1SG}
      >
        <meshStandardMaterial {...materials.phong1SG} color={props.color} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Balloon.glb");
