/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ComputerScreen.glb -o src/components/ComputerScreen.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ComputerScreen(props) {
  const { nodes, materials } = useGLTF("/models/ComputerScreen.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="computerScreen_2"
        geometry={nodes.computerScreen_2.geometry}
        material={materials.metalDark}
      />
      <mesh
        name="computerScreen_2_1"
        geometry={nodes.computerScreen_2_1.geometry}
        material={materials.metal}
      />
      <mesh
        name="computerScreen_3"
        geometry={nodes.computerScreen_3.geometry}
        material={materials.metal}
      />
      <mesh
        name="computerScreen_3_1"
        geometry={nodes.computerScreen_3_1.geometry}
        material={materials.metalDark}
      />
    </group>
  );
}

useGLTF.preload("/models/ComputerScreen.glb");
