/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CouchSmall.glb -o src/components/CouchSmall.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CouchSmall(props) {
  const { nodes, materials } = useGLTF("/models/CouchSmall.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Couch_Small1" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          name="Couch_Small1_1"
          geometry={nodes.Couch_Small1_1.geometry}
          material={materials.Couch_Blue}
        />
        <mesh
          name="Couch_Small1_2"
          geometry={nodes.Couch_Small1_2.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/CouchSmall.glb");
