/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Lamp.glb -o src/components/Lamp.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Lamp(props) {
  const { nodes, materials } = useGLTF("/models/Lamp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="lampRoundFloor_2"
        geometry={nodes.lampRoundFloor_2.geometry}
        material={materials.metal}
      />
      <mesh
        name="lampRoundFloor_2_1"
        geometry={nodes.lampRoundFloor_2_1.geometry}
        material={materials.lamp}
      />
      <mesh
        name="lampRoundFloor_3"
        geometry={nodes.lampRoundFloor_3.geometry}
        material={materials.lamp}
      />
      <mesh
        name="lampRoundFloor_3_1"
        geometry={nodes.lampRoundFloor_3_1.geometry}
        material={materials.metal}
      />
    </group>
  );
}

useGLTF.preload("/models/Lamp.glb");
