/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Mailbox.glb -o src/components/Mailbox.jsx -k -r public 
*/

import React, { useEffect, useState } from "react";
import { useCursor, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { config } from "../config";

export function Mailbox(props) {
  const { nodes, materials } = useGLTF("/models/Mailbox.glb");
  const [mailBoxHovered, setMailBoxHovered] = useState(false);
  useCursor(mailBoxHovered);

  useEffect(() => {
    const emissiveColor = new THREE.Color("#ffc527");
    Object.values(materials).forEach((material) => {
      material.emissive = emissiveColor;
    });
  });

  useFrame(() => {
    Object.values(materials).forEach((material) => {
      material.emissiveIntensity = THREE.MathUtils.lerp(
        material.emissiveIntensity,
        mailBoxHovered ? 0.32 : 0,
        0.1
      );
    });
  });
  return (
    <group
      {...props}
      dispose={null}
      onPointerEnter={() => setMailBoxHovered(true)}
      onPointerLeave={() => setMailBoxHovered(false)}
      onClick={() => window.open(`mailto:${config.contact.mail}`)}
    >
      <mesh
        name="group2028911354"
        geometry={nodes.group2028911354.geometry}
        material={materials.mat17}
      />
      <mesh
        name="group513383197"
        geometry={nodes.group513383197.geometry}
        material={materials.mat17}
      />
      <mesh
        name="group1044609393"
        geometry={nodes.group1044609393.geometry}
        material={materials.mat17}
      />
      <mesh
        name="group62313567"
        geometry={nodes.group62313567.geometry}
        material={materials.mat8}
      />
      <mesh
        name="group1018199070"
        geometry={nodes.group1018199070.geometry}
        material={materials.mat20}
      />
      <mesh
        name="group1855928084"
        geometry={nodes.group1855928084.geometry}
        material={materials.mat16}
      />
      <mesh
        name="group2114715230"
        geometry={nodes.group2114715230.geometry}
        material={materials.mat16}
      />
      <mesh
        name="group961800690"
        geometry={nodes.group961800690.geometry}
        material={materials.mat16}
      />
      <mesh
        name="group2098010904"
        geometry={nodes.group2098010904.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1048902298"
        geometry={nodes.group1048902298.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group698486446"
        geometry={nodes.group698486446.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group513376890"
        geometry={nodes.group513376890.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group2003878409"
        geometry={nodes.group2003878409.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1278976230"
        geometry={nodes.group1278976230.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group823787471"
        geometry={nodes.group823787471.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1640785644"
        geometry={nodes.group1640785644.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group774986514"
        geometry={nodes.group774986514.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group163990428"
        geometry={nodes.group163990428.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group502275761"
        geometry={nodes.group502275761.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1083102086"
        geometry={nodes.group1083102086.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1169220911"
        geometry={nodes.group1169220911.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group819034674"
        geometry={nodes.group819034674.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group2122795285"
        geometry={nodes.group2122795285.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1086767079"
        geometry={nodes.group1086767079.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1548836198"
        geometry={nodes.group1548836198.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1787203505"
        geometry={nodes.group1787203505.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group781068275"
        geometry={nodes.group781068275.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1179346883"
        geometry={nodes.group1179346883.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group731433140"
        geometry={nodes.group731433140.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1547746947"
        geometry={nodes.group1547746947.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1121282222"
        geometry={nodes.group1121282222.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group480589545"
        geometry={nodes.group480589545.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group796041224"
        geometry={nodes.group796041224.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1339086745"
        geometry={nodes.group1339086745.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group195866"
        geometry={nodes.group195866.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1743123278"
        geometry={nodes.group1743123278.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group1580040935"
        geometry={nodes.group1580040935.geometry}
        material={materials.mat10}
      />
      <mesh
        name="group804677075"
        geometry={nodes.group804677075.geometry}
        material={materials.mat20}
      />
    </group>
  );
}

useGLTF.preload("/models/Mailbox.glb");
