/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Palmtree.glb -o src/components/PalmTree.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PalmTree(props) {
  const { nodes, materials } = useGLTF("/models/Palmtree.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="PalmyraPalmTree_mesh"
        geometry={nodes.PalmyraPalmTree_mesh.geometry}
        material={materials.PalmyraPalmTree_mat}
      />
    </group>
  );
}

useGLTF.preload("/models/Palmtree.glb");
