/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Star(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Star.gltf");
  useFrame(() => {
    group.current.rotation.y += 0.06;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.star.geometry}
        material={materials["Yellow.030"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/star/model.gltf"
);
